Some more config massaging for `.wast` tests and GC and fuzzing (#13294)
Should hopefully resolve issues I'm seeing in CI like

```
failures:

---- oracles::tests::wast_smoke_test stdout ----

thread 'oracles::tests::wast_smoke_test' (7102) panicked at crates/fuzzing/src/oracles.rs:777:10:
called `Result::unwrap()` on an `Err` value: failed directive on /home/runner/work/wasmtime/wasmtime/tests/misc_testsuite/gc/binary-tree.wast:64

Caused by:
    0: error while executing at wasm backtrace:
    0:     0x82 - <unknown>!build
    1:     0x67 - <unknown>!build
    2:     0x67 - <unknown>!build
    3:     0x67 - <unknown>!build
    4:     0x67 - <unknown>!build
    5:     0xb3 - <unknown>!<wasm function 3>
note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    1: GC heap out of memory: no capacity for allocation of 40 bytes

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    oracles::tests::wast_smoke_test
```

https://github.com/bytecodealliance/wasmtime/actions/runs/25401865884/job/74503282576#step:4:489